/*
 * Copyright © 2026 Trevin Beattie
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
package com.xmission.trevin.android.notes.service;

import static com.xmission.trevin.android.notes.data.NotePreferences.*;
import static com.xmission.trevin.android.notes.service.XMLExporter.*;
import static com.xmission.trevin.android.notes.service.XMLImporterTests.assertNoteEquals;
import static com.xmission.trevin.android.notes.service.XMLImporterTests.compareNoteRecords;
import static com.xmission.trevin.android.notes.service.XMLImporterTests.getKey;
import static com.xmission.trevin.android.notes.service.XMLImporterTests.TEST_CATEGORIES_1;
import static com.xmission.trevin.android.notes.service.XMLImporterTests.TEST_CATEGORIES_2;
import static com.xmission.trevin.android.notes.service.XMLImporterTests.TEST_NOTES_1;
import static com.xmission.trevin.android.notes.service.ZIPExporter.METADATA_DIR;
import static com.xmission.trevin.android.notes.service.ZIPExporter.METADATA_FILE;
import static com.xmission.trevin.android.notes.service.ZIPExporter.PREFS_FILE;
import static com.xmission.trevin.android.notes.util.RandomNoteUtils.*;

import static org.junit.Assert.*;

import com.xmission.trevin.android.notes.data.*;
import com.xmission.trevin.android.notes.provider.MockNoteRepository;
import com.xmission.trevin.android.notes.provider.NoteCursor;
import com.xmission.trevin.android.notes.provider.NoteRepositoryImpl;
import com.xmission.trevin.android.notes.provider.NoteSchema;
import com.xmission.trevin.android.notes.service.ZIPImporter.ImportType;
import com.xmission.trevin.android.notes.util.*;

import net.lingala.zip4j.ZipFile;
import net.lingala.zip4j.model.ZipParameters;
import net.lingala.zip4j.model.enums.AesKeyStrength;
import net.lingala.zip4j.model.enums.EncryptionMethod;

import org.apache.commons.lang3.RandomStringUtils;
import org.apache.commons.lang3.StringUtils;
import org.json.JSONException;
import org.json.JSONObject;
import org.junit.After;
import org.junit.Before;
import org.junit.BeforeClass;
import org.junit.Test;

import java.io.ByteArrayInputStream;
import java.io.ByteArrayOutputStream;
import java.io.File;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.InputStream;
import java.io.PrintStream;
import java.nio.charset.StandardCharsets;
import java.time.Instant;
import java.time.ZoneOffset;
import java.time.format.DateTimeFormatter;
import java.util.*;
import java.util.zip.ZipEntry;
import java.util.zip.ZipOutputStream;

/**
 * Unit tests for importing notes from a ZIP file.
 *
 * @author Trevin Beattie
 */
public class ZIPImporterTests {

    public static final Random RAND = new Random();
    public static final RandomStringUtils SRAND = RandomStringUtils.insecure();

    private static MockSharedPreferences underlyingPrefs = null;
    private static NotePreferences mockPrefs = null;
    private static MockNoteRepository mockRepo = null;
    private StringEncryption globalEncryption = null;
    private static String unfiledName = "Unfiled";

    @BeforeClass
    public static void initializeMocks() {
        underlyingPrefs = MockSharedPreferences.getInstance();
        NotePreferences.setSharedPreferences(underlyingPrefs);
        mockPrefs = NotePreferences.getInstance(null);
        mockRepo = MockNoteRepository.getInstance();
        unfiledName = mockRepo.getCategoryById(NoteCategory.UNFILED).getName();
    }

    @Before
    public void resetMocks() {
        underlyingPrefs.resetMock();
        mockRepo.clear();
        globalEncryption = StringEncryption.holdGlobalEncryption();
        globalEncryption.forgetPassword();
    }

    @After
    public void cleanUp() {
        globalEncryption.forgetPassword();
        StringEncryption.releaseGlobalEncryption();
    }

    /**
     * Generate a temporary ZIP file for testing the import.
     * This uses Java&rsquo;s built-in ZIP methods to ensure that
     * the Zip4j reader is compatible with files generated by
     * other applications.  However, it <i>cannot</i> handle
     * encrypted entries using standard ZIP encryption methods.
     *
     * @param tag a label to include in the temporary file name
     * identifying which test is generating it.
     * @param includeComment whether to add a file-level JSON comment
     * in the ZIP file.  This will generate the standard key/value pairs
     * used by {@link ZIPExporter}.
     * @param directories ZIP entries for any directories to add to the
     * ZIP file.  These will always be added first.
     * @param files pairs of ZIP entries and input streams for files
     * to add to the ZIP file.
     *
     * @return the temporary file
     *
     * @throws IOException if there was an error writing the ZIP file
     * @throws JSONException if we made a mistake creating the JSON comment
     */
    private static File createTestZip(
            String tag, boolean includeComment,
            List<ZipEntry> directories,
            List<Map.Entry<ZipEntry, InputStream>> files)
            throws IOException, JSONException {
        File tempFile = File.createTempFile("notes-" + tag + "-", ".zip");
        tempFile.deleteOnExit();
        try (FileOutputStream oStream = new FileOutputStream(tempFile);
             ZipOutputStream out = new ZipOutputStream(oStream)) {
            if (includeComment) {
                JSONObject comment = new JSONObject();
                comment.put(ATTR_VERSION, 2);
                comment.put(ATTR_DB_VERSION,
                        NoteRepositoryImpl.DATABASE_VERSION);
                comment.put(ATTR_EXPORTED, Instant.now()
                        .atOffset(ZoneOffset.UTC)
                        .format(DateTimeFormatter.ISO_INSTANT));
                comment.put(ATTR_TOTAL_RECORDS,
                        directories.size() + files.size());
                out.setComment(comment.toString());
            }
            for (ZipEntry entry : directories) {
                out.putNextEntry(entry);
                out.closeEntry();
            }
            for (Map.Entry<ZipEntry, InputStream> file : files) {
                out.putNextEntry(file.getKey());
                byte[] buffer = new byte[8192];
                int len;
                while ((len = file.getValue().read(buffer)) > 0)
                    out.write(buffer, 0, len);
                file.getValue().close();
                out.closeEntry();
            }
        }
        return tempFile;
    }

    /**
     * Generate an entry for a category directory in a ZIP file.  The
     * directory name is created from the category name simply by
     * stripping any trailing periods and appending the file separator.
     *
     * @param category the category whose directory to create
     *
     * @return the ZIP entry
     *
     * @throws JSONException if we made a mistake creating the JSON comment
     */
    private static ZipEntry makeCategoryDirectory(NoteCategory category)
            throws JSONException {
        JSONObject comment = new JSONObject();
        comment.put(ATTR_ID, category.getId());
        comment.put(ATTR_NAME, category.getName());
        String dirName = category.getName().replaceAll("\\.+$", "")
                + File.separator;
        ZipEntry dirEntry = new ZipEntry(dirName);
        dirEntry.setComment(comment.toString());
        return dirEntry;
    }

    /**
     * Generate an entry for a note from NotePad.
     *
     * @param note the note to create.  This note <i>must not</i> be
     * modified before the ZIP file is created.  If the note is encrypted,
     * this will assume we are writing the raw encrypted note to the ZIP
     * file; <i>no dot use this method</i> if we need to use ZIP encryption.
     * If the note is in any category other than &ldquo;Unfiled&rdquo;,
     * its {@code categoryName} field <b>must</b> be set.
     *
     * @return a {@link Map.Entry} with the ZIP entry and input stream for
     * the note content.
     *
     * @throws JSONException if we made a mistake creating the JSON comment
     */
    private static Map.Entry<ZipEntry,InputStream> makeNoteFile(
            NoteItem note) throws JSONException {
        JSONObject comment = new JSONObject();
        comment.put(ATTR_ID, note.getId());
        comment.put(NOTE_CREATED, note.getCreateTime().toString());
        comment.put(NOTE_MODIFIED, note.getModTime().toString());
        if (note.isPrivate()) {
            comment.put(ATTR_PRIVATE, true);
            if (note.isEncrypted())
                comment.put(ATTR_ENCRYPTION, note.getPrivate());
        }
        StringBuilder fileName = new StringBuilder();
        if (note.getCategoryId() != NoteCategory.UNFILED) {
            fileName.append(note.getCategoryName()
                    .replaceAll("\\.+$", ""));
            fileName.append(File.separator);
        }
        fileName.append(note.getId());
        InputStream fileStream;
        if (note.isEncrypted()) {
            fileName.append(" - Locked.aes");
            fileStream = new ByteArrayInputStream(note.getEncryptedNote());
        } else {
            String title = note.getNote();
            if (title.length() > 40)
                title = title.substring(0, 40);
            if (title.contains("\n"))
                title = title.substring(0, title.indexOf('\n'));
            if (title.contains("."))
                title = title.substring(0, title.indexOf('.'));
            fileName.append(" - ").append(title).append(".txt");
            fileStream = new ByteArrayInputStream(note.getNote()
                    .getBytes(StandardCharsets.UTF_8));
        }
        ZipEntry fileEntry = new ZipEntry(fileName.toString());
        fileEntry.setComment(comment.toString());
        return Map.entry(fileEntry, fileStream);
    }

    /**
     * Run the importer for a given test file.  The operation is expected
     * to run successfully.
     *
     * @param zipFile the ZIP file to import
     * @param importType the type of import to perform.
     * @param importPrivate whether to include private records.
     * @param zipPassword the password with which the ZIP file was
     * exporter, or {@code null}
     *
     * @return the progress indicator at the end of the import
     *
     * @throws IOException if there was an error reading the import file.
     * @throws RuntimeException if the import failed.
     */
    private MockProgressBar runImporter(
            File zipFile, ImportType importType,
            boolean importPrivate, char[] zipPassword)
        throws IOException {
        char[] currentPassword = null;
        if (globalEncryption.hasKey())
            currentPassword = Arrays.copyOf(globalEncryption.getPassword(),
                    globalEncryption.getPassword().length);
        assertTrue(String.format("Import test file %s does not exist",
                zipFile.getAbsolutePath()), zipFile.exists());
        MockProgressBar progress = new MockProgressBar();
        ZIPImporter importer = new ZIPImporter(mockPrefs, mockRepo,
                progress);
        importer.importData(zipFile.getName(), zipFile, importType,
                importPrivate, zipPassword, currentPassword);
        progress.setEndTime();
        return progress;
    }

    /**
     * Test reading an empty ZIP file.
     */
    @Test
    public void testImportEmptyNoComment()
            throws IOException, JSONException {
        File zipFile = createTestZip("empty", false,
                Collections.emptyList(), Collections.emptyList());
        MockProgressBar progress = runImporter(zipFile,
                ImportType.TEST, false, null);
        MockProgressBar.Progress lastProgress = progress.getEndProgress();
        assertNotNull("Progress meter was not updated", lastProgress);
        assertEquals("Total number of records determined",
                -1, lastProgress.total);
        assertEquals("Number of records processed",
                0, lastProgress.current);
    }

    /**
     * Test reading an empty ZIP file created by our {@link ZIPExporter}.
     */
    @Test
    public void testImportEmptyWithComment()
        throws IOException, JSONException {
        File zipFile = createTestZip("empty", true,
                Collections.emptyList(), Collections.emptyList());
        MockProgressBar progress = runImporter(zipFile,
                ImportType.TEST, false, null);
        MockProgressBar.Progress lastProgress = progress.getEndProgress();
        assertNotNull("Progress meter was not updated", lastProgress);
        assertEquals("Total number of records determined",
                0, lastProgress.total);
        assertEquals("Number of records processed",
                0, lastProgress.current);
    }

    /**
     * Generate a set of preferences for testing
     *
     * @return a Map of preferences
     */
    private static Map<String,?> randomPrefs() {
        Map<String,Object> prefs = new TreeMap<>();
        prefs.put(NPREF_SCROLL_THRESHOLD, (float)
                Math.exp(4.0 * RAND.nextDouble() - 3.0));
        prefs.put(NPREF_SELECTED_CATEGORY, RAND.nextLong(1000));
        prefs.put(NPREF_SHOW_CATEGORY, RAND.nextBoolean());
        prefs.put(NPREF_SHOW_PRIVATE, RAND.nextBoolean());
        prefs.put(NPREF_SHOW_ENCRYPTED, RAND.nextBoolean());
        prefs.put(NPREF_SORT_ORDER, RAND.nextInt(10) + 1);
        prefs.put(NPREF_EXPORT_FILE, SRAND.nextAlphanumeric(32));
        prefs.put(NPREF_EXPORT_PRIVATE, RAND.nextBoolean());
        prefs.put(NPREF_IMPORT_FILE, SRAND.nextAlphanumeric(32));
        prefs.put(NPREF_IMPORT_TYPE, RAND.nextInt(ImportType.values().length));
        prefs.put(NPREF_IMPORT_PRIVATE, RAND.nextBoolean());
        return prefs;
    }

    /**
     * Generate a preferences XML file from a set of test preferences
     * for testing.
     *
     * @param prefsMap the preferences to write to XML
     *
     * @return an InputStream on the buffered XML document
     */
    private static InputStream getPrefsXML(Map<String,?> prefsMap) {
        ByteArrayOutputStream bs = new ByteArrayOutputStream();
        PrintStream out = new PrintStream(bs);
        out.println("<?xml version=\"1.0\" encoding=\"utf-8\"?>");
        out.printf(Locale.US, "<%s %s=\"%d\">\n",
                PREFERENCES_TAG, ATTR_COUNT, prefsMap.size());
        for (String key : prefsMap.keySet()) {
            Object value = prefsMap.get(key);
            out.printf(Locale.US, "  <%s>%s</%s>\n",
                    key, escapeXML((value == null) ? null
                            : value.toString()), key);
        }
        out.printf(Locale.US, "</%s>\n", PREFERENCES_TAG);
        out.close();
        return new ByteArrayInputStream(bs.toByteArray());
    }

    /**
     * Test reading preferences.
     */
    @Test
    public void testImportPreferences()
            throws IOException, JSONException {
        Map<String,?> prefsMap = randomPrefs();
        InputStream prefsContent = getPrefsXML(prefsMap);
        File zipFile = createTestZip("prefs", true,
                Collections.singletonList(new ZipEntry(METADATA_DIR)),
                Collections.singletonList(Map.entry(
                        new ZipEntry(PREFS_FILE), prefsContent)));
        MockProgressBar progress = runImporter(zipFile,
                ImportType.UPDATE, false, null);

        assertEquals(NPREF_SORT_ORDER, prefsMap.get(NPREF_SORT_ORDER),
                mockPrefs.getSortOrder());
        assertEquals(NPREF_SHOW_CATEGORY, prefsMap.get(NPREF_SHOW_CATEGORY),
                mockPrefs.showCategory());
        // The importer should not have changed the "Show Private" flag
        assertNull(NPREF_SHOW_PRIVATE,
                underlyingPrefs.getPreference(NPREF_SHOW_PRIVATE));
        // The import MUST NOT have changed the "Show Encrypted" flag
        assertNull(NPREF_SHOW_ENCRYPTED,
                underlyingPrefs.getPreference(NPREF_SHOW_ENCRYPTED));
        assertEquals(NPREF_SCROLL_THRESHOLD,
                prefsMap.get(NPREF_SCROLL_THRESHOLD),
                mockPrefs.getScrollBarThreshold());
        // We do not expect the importer to change any of the
        // Export / Import preferences.
        assertNull(NPREF_EXPORT_FILE,
                underlyingPrefs.getPreference(NPREF_EXPORT_FILE));
        assertNull(NPREF_EXPORT_PRIVATE,
                underlyingPrefs.getPreference(NPREF_EXPORT_PRIVATE));
        assertNull(NPREF_IMPORT_FILE,
                underlyingPrefs.getPreference(NPREF_IMPORT_FILE));
        assertNull(NPREF_IMPORT_TYPE,
                underlyingPrefs.getPreference(NPREF_IMPORT_TYPE));
        assertNull(NPREF_IMPORT_PRIVATE,
                underlyingPrefs.getPreference(NPREF_IMPORT_PRIVATE));

        MockProgressBar.Progress lastProgress = progress.getEndProgress();
        assertNotNull("Progress meter was not updated", lastProgress);
        assertEquals("Total number of records determined",
                2, lastProgress.total);
        assertEquals("Number of records processed",
                2, lastProgress.current);
    }

    /**
     * Test reading preferences in test mode.
     */
    @Test
    public void testImportPreferencesTest()
            throws IOException, JSONException {
        Map<String,?> prefsMap = randomPrefs();
        InputStream prefsContent = getPrefsXML(prefsMap);
        File zipFile = createTestZip("prefs", true,
                Collections.singletonList(new ZipEntry(METADATA_DIR)),
                Collections.singletonList(Map.entry(
                        new ZipEntry(PREFS_FILE), prefsContent)));
        MockProgressBar progress = runImporter(zipFile,
                ImportType.TEST, false, null);
        MockProgressBar.Progress lastProgress = progress.getEndProgress();
        assertEquals("Preferences were changed",
                Collections.emptyMap(), underlyingPrefs.getAll());
        assertNotNull("Progress meter was not updated", lastProgress);
        assertEquals("Total number of records determined",
                2, lastProgress.total);
        assertEquals("Number of records processed",
                2, lastProgress.current);
    }

    /**
     * Generate a metadata XML file from a set of test metadata.
     *
     * @param metadata the metadata to write to XML
     *
     * @return an InputStream on the buffered XML document
     */
    private static InputStream getMetadataXML(List<NoteMetadata> metadata) {
        ByteArrayOutputStream bs = new ByteArrayOutputStream();
        PrintStream out = new PrintStream(bs);
        out.println("<?xml version=\"1.0\" encoding=\"utf-8\"?>");
        out.printf(Locale.US, "<%s %s=\"%d\">\n",
                METADATA_TAG, ATTR_COUNT, metadata.size());
        for (NoteMetadata metadatum : metadata) {
            String value64 = (metadatum.getValue() == null) ? null
                    : encodeBase64(metadatum.getValue());
            out.printf(Locale.US, "  <%s %s=\"%d\" %s=\"%s\"",
                    METADATA_ITEM, ATTR_ID, metadatum.getId(), ATTR_NAME,
                    escapeXML(metadatum.getName()));
            if (value64 != null)
                out.printf(Locale.US, ">%s</%s>\n", value64, METADATA_ITEM);
            else
                out.printf(Locale.US, "/>\n");
        }
        out.printf(Locale.US, "</%s>\n", METADATA_TAG);
        out.close();
        return new ByteArrayInputStream(bs.toByteArray());
    }

    /**
     * Test reading metadata.  This doesn&rsquo;t actually get imported.
     */
    @Test
    public void testImportMetadata()
        throws IOException, JSONException {
        List<NoteMetadata> metadata = new ArrayList<>();
        for (int i = RAND.nextInt(4) + 3; i >= 0; --i) {
            byte[] content = new byte[RAND.nextInt(4, 36)];
            RAND.nextBytes(content);
            NoteMetadata metadatum = mockRepo.upsertMetadata(
                    SRAND.nextAlphanumeric(15), content);
            metadata.add(metadatum);
        }
        InputStream metaContent = getMetadataXML(metadata);
        File zipFile = createTestZip("metadata", true,
                Collections.singletonList(new ZipEntry(METADATA_DIR)),
                Collections.singletonList(Map.entry(
                        new ZipEntry(METADATA_FILE), metaContent)));
        MockProgressBar progress = runImporter(zipFile,
                ImportType.TEST, false, null);

        MockProgressBar.Progress lastProgress = progress.getEndProgress();
        assertNotNull("Progress meter was not updated", lastProgress);
        assertEquals("Total number of records determined",
                2, lastProgress.total);
        assertEquals("Number of records processed",
                2, lastProgress.current);
    }

    /**
     * Create a ZIP file containing just the metadata for a password hash.
     * This is used by several password check tests.
     *
     * @param password the password to hash and store in the ZIP file
     *
     * @return the generated ZIP file
     */
    private File makePasswordProtectedZIP(char[] password)
            throws IOException, JSONException {
        StringEncryption se = new StringEncryption();
        se.setPassword(password);
        se.addSalt();
        se.storePassword(mockRepo);
        NoteMetadata hash = mockRepo.getMetadataByName(
                StringEncryption.METADATA_PASSWORD_HASH);
        InputStream metaContent = getMetadataXML(
                Collections.singletonList(hash));
        return createTestZip("bundledPassword", true,
                Collections.singletonList(new ZipEntry(METADATA_DIR)),
                Collections.singletonList(Map.entry(
                        new ZipEntry(METADATA_FILE), metaContent)));
    }

    /**
     * Test checking the password against the metadata stored in the
     * ZIP file.
     */
    @Test
    public void testCheckZIPPasswordMatch()
            throws IOException, JSONException {
        char[] password = SRAND.nextAlphanumeric(12).toCharArray();
        File zipFile = makePasswordProtectedZIP(password);
        runImporter(zipFile, ImportType.TEST, true, password);
    }

    /**
     * Test checking an invalid password hash against the metadata
     * stored in the ZIP file.
     */
    @Test
    public void testCheckZIPPasswordMismatch()
            throws IOException, JSONException {
        char[] correctPassword = SRAND.nextAlphanumeric(12).toCharArray();
        File zipFile = makePasswordProtectedZIP(correctPassword);
        char[] wrongPassword = SRAND.nextAlphanumeric(11).toCharArray();
        try {
            runImporter(zipFile, ImportType.TEST, true,
                    wrongPassword);
            fail("Import completed successfully");
        } catch (PasswordMismatchException e) {
            String lmsg = e.getMessage().toLowerCase(Locale.US);
            assertTrue("Exception thrown but does not mention password mismatch",
                    lmsg.contains("password") && lmsg.contains("match"));
        }
    }

    /**
     * Test checking an import which is password-protected (using our
     * bundled encryption) but no password is provided.
     */
    @Test
    public void testCheckZIPPasswordRequired()
            throws IOException, JSONException {
        char[] password = SRAND.nextAlphanumeric(12).toCharArray();
        File zipFile = makePasswordProtectedZIP(password);
        try {
            runImporter(zipFile, ImportType.TEST, true, null);
            fail("Import completed successfully");
        } catch (PasswordRequiredException e) {
            String lmsg = e.getMessage().toLowerCase(Locale.US);
            assertTrue("Exception thrown but does not mention password",
                    lmsg.contains("password"));
        }
    }

    /**
     * Create a ZIP file containing the categories from
     * {@link XMLImporterTests#TEST_CATEGORIES_1}.
     * This is used in several category import tests.
     *
     * @param tag a label to include in the temporary file name
     * identifying which test is generating it.
     *
     * @return the generated ZIP file
     */
    private File generateTestCategories1ZIP(String tag)
        throws IOException, JSONException {
        List<ZipEntry> directories = new ArrayList<>();
        for (NoteCategory category : TEST_CATEGORIES_1)
            directories.add(makeCategoryDirectory(category));
        return createTestZip(tag, true,
                directories, Collections.emptyList());
    }

    /**
     * Add some random categories to the mock repository.
     * This uses some of the same ID&rsquo;s and names as those
     * in {@link XMLImporterTests#TEST_CATEGORIES_1}, but not
     * necessarily the same mapping in order to check potential
     * replacements or reassignments.
     *
     * @return a new {@link Map} of the categories that were added
     */
    private SortedMap<Long,String> addRandomCategories() {
        SortedMap<Long,String> testCategories = new TreeMap<>();
        for (int i = 8 + RAND.nextInt(5); i >= 0; --i) {
            NoteCategory cat = new NoteCategory();
            do {
                cat.setId(RAND.nextInt(20) + 1);
                if (RAND.nextBoolean())
                    cat.setName(TEST_CATEGORIES_1.get(
                            RAND.nextInt(TEST_CATEGORIES_1.size()))
                            .getName());
                else
                    cat.setName(randomWord() + " " + randomWord());
            }
            // Verify that there are no duplicates within this set
            while (testCategories.containsKey(cat.getId()) ||
                    testCategories.containsValue(cat.getName()));
            mockRepo.insertCategory(cat);
            testCategories.put(cat.getId(), cat.getName());
        }
        return testCategories;
    }

    /**
     * Read all categories from the mock repository into a {@link Map}
     *
     * @return the category map
     */
    private SortedMap<Long,String> readCategories() {
        SortedMap<Long,String> categoryMap = new TreeMap<>();
        List<NoteCategory> categories = mockRepo.getCategories();
        for (NoteCategory cat : categories)
            categoryMap.put(cat.getId(), cat.getName());
        return categoryMap;
    }

    /**
     * Verify the imported categories.
     *
     * @param expectedCategories the categories we expect to be in the
     * database.  This method will add the default &ldquo;Unfiled&rdquo;
     * category.
     *
     * @throws AssertionError if the actual categories do not match
     */
    private void assertCategoriesEquals(Map<Long,String> expectedCategories)
            throws AssertionError {
        SortedMap<Long,String> actualCategories = readCategories();
        assertCategoriesEquals(expectedCategories, actualCategories);
    }

    private void assertCategoriesEquals(
            Map<Long,String> expectedCategories,
            Map<Long,String> actualCategories) throws AssertionError {
        expectedCategories.put((long) NoteCategory.UNFILED, unfiledName);
        assertEquals("Imported categories",
                expectedCategories, actualCategories);
    }

    /**
     * Test a clean import of categories.
     * All existing categories must be replaced.
     */
    @Test
    public void testImportCategoriesClean()
            throws IOException, JSONException {

        File zipFile = generateTestCategories1ZIP("cat-clean");
        addRandomCategories();
        MockProgressBar progress = runImporter(zipFile,
                ImportType.CLEAN, false, null);

        SortedMap<Long,String> expectedCategories = new TreeMap<>();
        for (NoteCategory cat : TEST_CATEGORIES_1)
            expectedCategories.put(cat.getId(), cat.getName());

        assertCategoriesEquals(expectedCategories);

        MockProgressBar.Progress endProgress = progress.getEndProgress();
        assertNotNull("Progress meter after import", endProgress);
        assertEquals("Total records in file",
                TEST_CATEGORIES_1.size(), endProgress.total);
        assertEquals("Number of records processed",
                TEST_CATEGORIES_1.size(), endProgress.current);

    }

    /**
     * Test importing categories in {@link ImportType#REVERT REVERT}
     * mode.  If a name conflicts with an existing entry in the database
     * all notes using the current category ID will be moved to
     * &ldquo;Unfiled&rdquo;.  If an ID conflicts with an existing entry
     * in the database, the category&rsquo;s name will be replaced.
     */
    @Test
    public void testImportCategoriesOverwrite()
            throws IOException, JSONException {

        File zipFile = generateTestCategories1ZIP("cat-revert");
        SortedMap<Long,String> expectedCategories = addRandomCategories();

        // Add one note using a category name that will be replaced
        NoteCategory dupCatName = null;
        List<Map.Entry<Long,String>> candidates =
                new ArrayList<>(expectedCategories.entrySet());
        while ((dupCatName == null) && !candidates.isEmpty()) {
            Map.Entry<Long,String> entry = candidates.get(
                    RAND.nextInt(candidates.size()));
            for (NoteCategory cat : TEST_CATEGORIES_1) {
                if (entry.getValue().equals(cat.getName()) &&
                        !entry.getKey().equals(cat.getId())) {
                    dupCatName = new NoteCategory();
                    dupCatName.setId(entry.getKey());
                    dupCatName.setName(entry.getValue());
                    break;
                }
            }
            if (dupCatName == null)
                candidates.remove(entry);
        }
        if (dupCatName == null) {
            // No usable category was created randomly; force one
            dupCatName = new NoteCategory();
            dupCatName.setId(RAND.nextInt(10) + 21);
            do {
                dupCatName.setName(TEST_CATEGORIES_1.get(
                        RAND.nextInt(TEST_CATEGORIES_1.size())).getName());
            } while (expectedCategories.containsValue(dupCatName.getName()));
            mockRepo.insertCategory(dupCatName);
            expectedCategories.put(dupCatName.getId(), dupCatName.getName());
        }

        NoteItem noteDupCatName = randomNote();
        noteDupCatName.setCategoryId(dupCatName.getId());
        noteDupCatName.setCategoryName(dupCatName.getName());
        mockRepo.insertNote(noteDupCatName);

        // Update our expectation for the item's revision.
        // (The mock repo contains a clone of the item, not our original.)
        noteDupCatName.setCategoryId(NoteCategory.UNFILED);
        noteDupCatName.setCategoryName(unfiledName);

        // Add one note using a category ID whose name will be changed
        NoteCategory dupCatId = null;
        candidates.clear();
        candidates.addAll(expectedCategories.entrySet());
        while ((dupCatId == null) && !candidates.isEmpty()) {
            Map.Entry<Long,String> entry = candidates.get(
                    RAND.nextInt(candidates.size()));
            for (NoteCategory cat : TEST_CATEGORIES_1) {
                if (entry.getKey().equals(cat.getId()) &&
                        !entry.getValue().equals(cat.getName())) {
                    // No imported categories are valid candidates
                    boolean newName = false;
                    for (NoteCategory cat2 : TEST_CATEGORIES_1) {
                        if (entry.getValue().equals(cat2.getName())) {
                            newName = true;
                            break;
                        }
                    }
                    if (newName) {
                        candidates.remove(entry);
                        continue;
                    }
                    dupCatId = new NoteCategory();
                    dupCatId.setId(entry.getKey());
                    dupCatId.setName(entry.getValue());
                    break;
                }
            }
        }
        if (dupCatId == null) {
            // No usable category was created randomly; force one
            dupCatId = new NoteCategory();
            do {
                dupCatId.setId(RAND.nextInt(10) + 1);
                dupCatId.setName(randomWord() + " " + randomWord());
            } while (expectedCategories.containsKey(dupCatId.getId()) ||
                    expectedCategories.containsValue(dupCatId.getName()));
            mockRepo.insertCategory(dupCatId);
            expectedCategories.put(dupCatId.getId(), dupCatId.getName());
        }

        NoteItem noteDupCatId = randomNote();
        noteDupCatId.setCategoryId(dupCatId.getId());
        noteDupCatId.setCategoryName(dupCatId.getName());
        mockRepo.insertNote(noteDupCatId);

        for (NoteCategory cat : TEST_CATEGORIES_1) {
            if (cat.getId().equals(dupCatId.getId())) {
                noteDupCatId.setCategoryName(cat.getName());
                break;
            }
        }

        MockProgressBar progress = runImporter(zipFile,
                ImportType.REVERT, false, null);

        // Set our category expectations
        for (NoteCategory cat : TEST_CATEGORIES_1) {
            if (expectedCategories.containsValue(cat.getName())) {
                Long id = getKey(expectedCategories, cat.getName());
                expectedCategories.remove(id);
            }
            expectedCategories.put(cat.getId(), cat.getName());
        }

        assertCategoriesEquals(expectedCategories);

        // Verify the category of the first note
        // was changed to Unfiled
        NoteItem actualItem = mockRepo.getNoteById(noteDupCatName.getId());
        List<String> diffs = compareNoteRecords(
                "Note formerly in category " + dupCatName.getName(),
                noteDupCatName, actualItem);
        if (!diffs.isEmpty())
            fail(StringUtils.join("\n", diffs));

        // Verify the category of the second note
        // just had its name changed
        actualItem = mockRepo.getNoteById(noteDupCatId.getId());
        diffs = compareNoteRecords(
                "Note with category #" + dupCatId.getId(),
                noteDupCatId, actualItem);
        if (!diffs.isEmpty())
            fail(StringUtils.join("\n", diffs));

        MockProgressBar.Progress endProgress = progress.getEndProgress();
        assertNotNull("Progress meter after import", endProgress);
        assertEquals("Total records in file",
                TEST_CATEGORIES_1.size(), endProgress.total);
        assertEquals("Number of records processed",
                TEST_CATEGORIES_1.size(), endProgress.current);

    }

    /**
     * Test importing categories in {@link ImportType#UPDATE UPDATE}
     * or {@link ImportType#ADD ADD} mode; the effect of all of these
     * are the same.  If we already have a category of the same name
     * but a different ID, the importer should use the existing ID.
     * If we have another category with the same ID as one being
     * imported, the imported category will get a new ID.  Otherwise
     * we&rsquo;ll try to add the category with its given ID.
     */
    private void testImportCategoriesUA(ImportType importType)
        throws IOException, JSONException {

        File zipFile = generateTestCategories1ZIP("cat-" + importType.name());
        SortedMap<Long,String> expectedCategories = addRandomCategories();

        // Add one note using a category name that has a different ID
        NoteCategory dupCatName = null;
        List<Map.Entry<Long,String>> candidates =
                new ArrayList<>(expectedCategories.entrySet());
        while ((dupCatName == null) && !candidates.isEmpty()) {
            Map.Entry<Long,String> entry = candidates.get(
                    RAND.nextInt(candidates.size()));
            for (NoteCategory cat : TEST_CATEGORIES_1) {
                if (entry.getValue().equals(cat.getName()) &&
                        !entry.getKey().equals(cat.getId())) {
                    dupCatName = new NoteCategory();
                    dupCatName.setId(entry.getKey());
                    dupCatName.setName(entry.getValue());
                    break;
                }
            }
            if (dupCatName == null)
                candidates.remove(entry);
        }
        if (dupCatName == null) {
            // No usable category was created randomly; force one
            dupCatName = new NoteCategory();
            dupCatName.setId(RAND.nextInt(10) + 21);
            do {
                dupCatName.setName(TEST_CATEGORIES_1.get(
                        RAND.nextInt(TEST_CATEGORIES_1.size())).getName());
            } while (expectedCategories.containsValue(dupCatName.getName()));
            mockRepo.insertCategory(dupCatName);
            expectedCategories.put(dupCatName.getId(), dupCatName.getName());
        }

        NoteItem noteDupCatName = randomNote();
        noteDupCatName.setCategoryId(dupCatName.getId());
        noteDupCatName.setCategoryName(dupCatName.getName());
        mockRepo.insertNote(noteDupCatName);

        // Add one note using a category ID that conflicts
        NoteCategory dupCatId = null;
        candidates.clear();
        candidates.addAll(expectedCategories.entrySet());
        while ((dupCatId == null) && !candidates.isEmpty()) {
            Map.Entry<Long,String> entry = candidates.get(
                    RAND.nextInt(candidates.size()));
            for (NoteCategory cat : TEST_CATEGORIES_1) {
                if (entry.getKey().equals(cat.getId()) &&
                        !entry.getValue().equals(cat.getName())) {
                    dupCatId = new NoteCategory();
                    dupCatId.setId(entry.getKey());
                    dupCatId.setName(entry.getValue());
                    break;
                }
            }
        }
        if (dupCatId == null) {
            // No usable category was created randomly; force one
            dupCatId = new NoteCategory();
            do {
                dupCatId.setId(RAND.nextInt(10) + 1);
                dupCatId.setName(randomWord() + " " + randomWord());
            } while (expectedCategories.containsKey(dupCatId.getId()) ||
                    expectedCategories.containsValue(dupCatId.getName()));
            mockRepo.insertCategory(dupCatId);
            expectedCategories.put(dupCatId.getId(), dupCatId.getName());
        }

        NoteItem noteDupCatId = randomNote();
        noteDupCatId.setCategoryId(dupCatId.getId());
        noteDupCatId.setCategoryName(dupCatId.getName());
        mockRepo.insertNote(noteDupCatId);

        // We won't know the ID's to expect for conflicting category
        // ID's until after the import.  Save these for later.
        Map<Long,String> expectedMoves = new TreeMap<>();
        for (NoteCategory cat : TEST_CATEGORIES_1) {
            if (expectedCategories.containsValue(cat.getName()))
                continue;  // This should not change any existing categories
            if (expectedCategories.containsKey(cat.getId())) {
                expectedMoves.put(cat.getId(), cat.getName());
                continue;
            }
            expectedCategories.put(cat.getId(), cat.getName());
        }

        MockProgressBar progress = runImporter(zipFile,
                importType, false, null);

        // Find the new ID's of categories which should have been moved
        SortedMap<Long,String> actualCategories = readCategories();
        for (Long id : expectedMoves.keySet()) {
            String catName = expectedMoves.get(id);
            assertTrue(String.format("Category \"%s\" was not imported"
                    + " (conflicting with category #%d)", catName, id),
                    actualCategories.containsValue(catName));
            // Add this to our full map of expected categories
            expectedCategories.put(
                    getKey(actualCategories, catName), catName);
        }

        // Now we can compare the full category maps
        assertCategoriesEquals(expectedCategories, actualCategories);

        // The notes should not have been changed
        NoteItem actualItem = mockRepo.getNoteById(noteDupCatName.getId());
        List<String> diffs = compareNoteRecords(String.format(
                        "Note in category #%d \"%s\"",
                        dupCatName.getId(), dupCatName.getName()),
                noteDupCatName, actualItem);
        if (!diffs.isEmpty())
            fail(StringUtils.join("\n", diffs));

        actualItem = mockRepo.getNoteById(noteDupCatId.getId());
        diffs = compareNoteRecords(String.format(
                        "Note in category #%d \"%s\"",
                        dupCatId.getId(), dupCatId.getName()),
                noteDupCatId, actualItem);
        if (!diffs.isEmpty())
            fail(StringUtils.join("\n", diffs));

        MockProgressBar.Progress endProgress = progress.getEndProgress();
        assertNotNull("Progress meter after import", endProgress);
        assertEquals("Total records in file",
                TEST_CATEGORIES_1.size(), endProgress.total);
        assertEquals("Number of records processed",
                TEST_CATEGORIES_1.size(), endProgress.current);

    }

    @Test
    public void testImportCategoriesUpdate()
            throws IOException, JSONException {
        testImportCategoriesUA(ImportType.UPDATE);
    }

    @Test
    public void testImportCategoriesAdd()
            throws IOException, JSONException {
        testImportCategoriesUA(ImportType.ADD);
    }

    /**
     * Create a ZIP file containing the categories from
     * {@link XMLImporterTests#TEST_CATEGORIES_2} and notes from
     * {@link XMLImporterTests#TEST_NOTES_1}.  This is used in
     * several note import tests.
     *
     * @param tag a label to include in the temporary file name
     * identifying which test is generating it.
     * @return the generated ZIP file
     */
    private File generateTestNotes1ZIP(String tag)
        throws IOException, JSONException {
        List<ZipEntry> directories = new ArrayList<>();
        for (NoteCategory category : TEST_CATEGORIES_2)
            directories.add(makeCategoryDirectory(category));
        List<Map.Entry<ZipEntry,InputStream>> files = new ArrayList<>();
        for (NoteItem note : TEST_NOTES_1)
            files.add(makeNoteFile(note));
        return createTestZip(tag, true, directories, files);
    }

    /**
     * Add all of the categories from
     * {@link XMLImporterTests#TEST_CATEGORIES_1} to the mock repository
     * and an assortment of random notes, some of which will have
     * conflicting ID&rsquo;s with records in
     * {@link XMLImporterTests#TEST_NOTES_1} and some will have categories
     * whose ID&rsquo;s conflict with records in
     * {@link XMLImporterTests#TEST_CATEGORIES_2}.
     *
     * @return a {@link List} of the notes that were added
     */
    private List<NoteItem> addRandomNotes() {
        for (NoteCategory cat : TEST_CATEGORIES_1)
            mockRepo.insertCategory(cat);

        List<NoteItem> newNotes = new ArrayList<>();
        Set<Long> usedIds = new HashSet<>();
        for (NoteItem note : TEST_NOTES_1)
            usedIds.add(note.getId());
        NoteItem note;
        NoteCategory cat;

        // Start with some notes which don't conflict with anything
        for (int i = RAND.nextInt(3) + 3; i >= 0; --i) {
            note = randomNote();
            cat = TEST_CATEGORIES_1.get(
                    RAND.nextInt(TEST_CATEGORIES_1.size()));
            note.setCategoryId(cat.getId());
            note.setCategoryName(cat.getName());
            do {
                note.setId(RAND.nextInt(1024) + 1);
            } while (usedIds.contains(note.getId()));
            mockRepo.insertNote(note);
            newNotes.add(note);
            usedIds.add(note.getId());
        }

        // Add some notes whose category ID's conflict with
        // TEST_CATEGORIES_2 (3, 4, or 5)
        for (NoteCategory inCat : TEST_CATEGORIES_2) {
            if (inCat.getId() - 1 >= TEST_CATEGORIES_1.size())
                continue;
            cat = TEST_CATEGORIES_1.get(inCat.getId().intValue() - 1);
            note = randomNote();
            note.setCategoryId(cat.getId());
            note.setCategoryName(cat.getName());
            do {
                note.setId(RAND.nextInt(1024) + 1);
            } while (usedIds.contains(note.getId()));
            mockRepo.insertNote(note);
            newNotes.add(note);
            usedIds.add(note.getId());
        }

        // Add one note from TEST_NOTES_1 with a conflicting ID
        note = randomNote();
        cat = TEST_CATEGORIES_1.get(
                RAND.nextInt(TEST_CATEGORIES_1.size()));
        note.setCategoryId(cat.getId());
        note.setCategoryName(cat.getName());
        NoteItem conflict = TEST_NOTES_1.get(RAND.nextInt(TEST_NOTES_1.size()));
        note.setId(conflict.getId());
        note.setCreateTime(conflict.getCreateTime());
        mockRepo.insertNote(note);
        newNotes.add(note);

        return newNotes;
    }

    /**
     * Read the current set of notes from the mock repository.
     * They should be sorted by ID.
     *
     * @return a {@link List} of notes.
     */
    private List<NoteItem> readNotes() {
        List<NoteItem> list = new ArrayList<>(TEST_NOTES_1.size());
        try (NoteCursor cursor = mockRepo.getNotes(
                ALL_CATEGORIES, true, true,
                NoteRepositoryImpl.NOTE_TABLE_NAME + "."
                        + NoteSchema.NoteItemColumns._ID)) {
            while (cursor.moveToNext())
                list.add(cursor.getNote());
        }
        return list;
    }

    /**
     * Test a clean import of public notes.
     * All existing notes must be replaced.
     */
    @Test
    public void testImportNotesClean1Public()
            throws IOException, JSONException {

        File zipFile = generateTestNotes1ZIP("clean");
        addRandomNotes();

        MockProgressBar progress = runImporter(zipFile,
                ImportType.CLEAN, false, null);

        SortedMap<Long,String> expectedCategories = new TreeMap<>();
        for (NoteCategory cat : TEST_CATEGORIES_2)
            expectedCategories.put(cat.getId(), cat.getName());
        assertCategoriesEquals(expectedCategories);

        List<NoteItem> expectedNotes = new ArrayList<>(TEST_NOTES_1.size());
        for (NoteItem note : TEST_NOTES_1) {
            if (!note.isPrivate())
                expectedNotes.add(note);
        }
        // Ensure the notes are sorted by ID
        Collections.sort(expectedNotes, MockNoteRepository.NOTE_ID_COMPARATOR);
        List<NoteItem> actualNotes = readNotes();

        assertNoteEquals("Imported notes", expectedNotes, actualNotes);

        MockProgressBar.Progress endProgress = progress.getEndProgress();
        assertNotNull("Progress meter after import", endProgress);
        int expectedRecordCount = TEST_CATEGORIES_2.size()
                + TEST_NOTES_1.size();
        assertEquals("Total records in file",
                expectedRecordCount, endProgress.total);
        assertEquals("Number of records processed",
                expectedRecordCount, endProgress.current);
    }

    /**
     * Test importing private (not password-protected) notes in
     * {@link ImportType#REVERT REVERT} mode.  Any existing notes
     * with the same ID as one from the XML import file should be
     * overwritten.
     */
    @Test
    public void testImportNotesRevertPrivate()
            throws IOException, JSONException {

        File zipFile = generateTestNotes1ZIP("revert");
        List<NoteItem> oldNotes = addRandomNotes();
        SortedMap<Long,String> expectedCategories = new TreeMap<>();
        for (NoteCategory cat : TEST_CATEGORIES_1)
            expectedCategories.put(cat.getId(), cat.getName());

        runImporter(zipFile, ImportType.REVERT, true, null);

        // For this operation we don't have any conflicting category names;
        // all categories between the two groups have unique names.
        // Categories with conflicting ID's will be replaced without
        // affecting the notes using those categories.
        for (NoteCategory cat : TEST_CATEGORIES_2)
            expectedCategories.put(cat.getId(), cat.getName());
        assertCategoriesEquals(expectedCategories);

        // Update the expectations for notes.
        Set<Long> newIds = new HashSet<>();
        List<NoteItem> expectedNotes = new ArrayList<>(
                oldNotes.size() + TEST_NOTES_1.size());
        for (NoteItem note : TEST_NOTES_1) {
            expectedNotes.add(note);
            newIds.add(note.getId());
        }
        for (NoteItem note : oldNotes) {
            if (newIds.contains(note.getId()))
                // This note should have been replaced; leave it out.
                continue;
            // Ensure the remaining old items are using the new category names
            note.setCategoryName(expectedCategories
                    .get(note.getCategoryId()));
            expectedNotes.add(note);
        }
        // Ensure the notes are sorted by ID
        Collections.sort(expectedNotes, MockNoteRepository.NOTE_ID_COMPARATOR);

        List<NoteItem> actualNotes = readNotes();

        assertNoteEquals("Imported notes", expectedNotes, actualNotes);
    }

    /**
     * Test importing public notes in {@link ImportType#ADD ADD} mode.
     * Any imported note with the same ID as an existing note will be
     * assigned a new ID regardless of its contents.
     */
    @Test
    public void testImportNotesAddPublic()
            throws IOException, JSONException {

        File zipFile = generateTestNotes1ZIP("add");
        List<NoteItem> oldNotes = addRandomNotes();
        SortedMap<Long,String> expectedCategories = new TreeMap<>();
        for (NoteCategory cat : TEST_CATEGORIES_1)
            expectedCategories.put(cat.getId(), cat.getName());

        // For this test we need a public note which exists in the import file.
        NoteItem alreadyImportedNote = null;
        while (alreadyImportedNote == null) {
            alreadyImportedNote = TEST_NOTES_1.get(RAND.nextInt(TEST_NOTES_1.size()));
            if ((alreadyImportedNote.getCategoryId() == NoteCategory.UNFILED) ||
                    alreadyImportedNote.isPrivate()) {
                alreadyImportedNote = null;
                continue;
            }
            for (NoteItem note : oldNotes) {
                if (note.getId().equals(alreadyImportedNote.getId())) {
                    alreadyImportedNote = null;
                    break;
                }
            }
        }
        NoteCategory alreadyImportedCategory = mockRepo.insertCategory(
                alreadyImportedNote.getCategoryName());
        expectedCategories.put(alreadyImportedCategory.getId(),
                alreadyImportedCategory.getName());
        alreadyImportedNote = alreadyImportedNote.clone();
        alreadyImportedNote.setCategoryId(alreadyImportedCategory.getId());
        alreadyImportedNote.setCreateTime(Instant.now().minusSeconds(
                RAND.nextInt(86400) + 86400));
        alreadyImportedNote.setModTime(alreadyImportedNote.getCreateTime());
        mockRepo.insertNote(alreadyImportedNote);
        oldNotes.add(alreadyImportedNote);

        runImporter(zipFile, ImportType.ADD, false, null);

        // The ID's of imported categories that conflict with existing
        // entries should change; we won't know what they are in advance.
        Map<String,Long> catNameMap = new HashMap<>();
        for (NoteCategory cat : mockRepo.getCategories())
            catNameMap.put(cat.getName(), cat.getId());
        for (NoteCategory cat : TEST_CATEGORIES_2)
            expectedCategories.put(catNameMap.get(cat.getName()), cat.getName());
        assertCategoriesEquals(expectedCategories);

        // Notes with a conflicting ID should be assigned a new ID,
        // which we can't determine until we've read the actual data.
        // Start with the non-conflicting notes.
        SortedMap<Long,NoteItem> expectedNotes = new TreeMap<>();
        for (NoteItem note : oldNotes)
            expectedNotes.put(note.getId(), note);
        Map<Long,NoteItem> conflictingNotes = new HashMap<>();
        for (NoteItem note : TEST_NOTES_1) {
            if (note.isPrivate())
                continue;
            if (expectedNotes.containsKey(note.getId())) {
                conflictingNotes.put(note.getId(), note);
                continue;
            }
            NoteItem newExpectation = note.clone();
            newExpectation.setCategoryId(
                    catNameMap.get(note.getCategoryName()));
            expectedNotes.put(note.getId(), newExpectation);
        }

        SortedMap<Long,NoteItem> actualNotes = new TreeMap<>();
        for (NoteItem note : readNotes()) {
            actualNotes.put(note.getId(), note);
            if (conflictingNotes.containsKey(note.getId()) &&
                    !expectedNotes.containsKey(note.getId())) {
                NoteItem newExpectation = conflictingNotes.get(
                        note.getId()).clone();
                newExpectation.setId(note.getId());
                newExpectation.setCategoryId(
                        catNameMap.get(note.getCategoryName()));
                expectedNotes.put(note.getId(), newExpectation);
                conflictingNotes.remove(note.getId());
            }
        }
        // If we have any remaining conflicts, ignore their ID's
        long nextAvailableId = -1;
        for (NoteItem note : conflictingNotes.values()) {
            NoteItem newExpectation = note.clone();
            newExpectation.setId(--nextAvailableId);
            newExpectation.setCategoryId(
                    catNameMap.get(note.getCategoryName()));
            expectedNotes.put(--nextAvailableId, newExpectation);
        }

        assertNoteEquals("Imported notes", expectedNotes, actualNotes);
    }

    /**
     * Test importing a private, encrypted note using bundled encryption.
     */
    @Test
    public void testImportBundledEncrypted()
            throws IOException, JSONException {

        NoteItem expectedNote = new NoteItem();
        expectedNote.setId(RAND.nextInt(128) + 16);
        expectedNote.setCategoryId(NoteCategory.UNFILED);
        expectedNote.setCategoryName(unfiledName);
        Instant now = Instant.now();
        expectedNote.setCreateTime(now.minusMillis(86400000
                + RAND.nextLong(31470552000L)));
        expectedNote.setModTime(expectedNote.getCreateTime()
                .plusMillis(RAND.nextLong(now.toEpochMilli()
                        - expectedNote.getCreateTime().toEpochMilli())));
        expectedNote.setPrivate(StringEncryption.encryptionType());

        final char[] oldPassword = SRAND.nextAlphanumeric(12).toCharArray();
        StringEncryption se = new StringEncryption();
        se.setPassword(oldPassword);
        se.addSalt();
        se.storePassword(mockRepo);

        String notePlainText = randomParagraph();
        expectedNote.setEncryptedNote(se.encrypt(notePlainText));

        NoteMetadata oldHash = mockRepo.getMetadataByName(
                StringEncryption.METADATA_PASSWORD_HASH);
        InputStream metaContent = getMetadataXML(
                Collections.singletonList(oldHash));

        List<Map.Entry<ZipEntry,InputStream>> files = new ArrayList<>();
        files.add(Map.entry(new ZipEntry(METADATA_FILE), metaContent));
        files.add(makeNoteFile(expectedNote));
        File zipFile = createTestZip("encrypted2", true,
                Collections.singletonList(new ZipEntry(METADATA_DIR)), files);

        se.forgetPassword();
        final char[] newPassword = SRAND.nextAlphanumeric(12).toCharArray();
        globalEncryption.setPassword(newPassword);
        globalEncryption.addSalt();
        globalEncryption.storePassword(mockRepo);
        // Update the encryption of the expected note to match the new password
        expectedNote.setEncryptedNote(globalEncryption.encrypt(notePlainText));

        runImporter(zipFile, ImportType.CLEAN, true, oldPassword);

        assertNoteEquals("Imported note",
                Collections.singletonList(expectedNote), readNotes());
    }

    /**
     * Generate an entry for a note from another source.
     *
     * @param directory an optional directory in which to put the note.
     * The caller needs to make sure a {@link ZipEntry} is created for
     * this directory.
     * @param note the content of the note to store.  A random name will
     * be generated for the entry.
     *
     * @return a {@link Map.Entry} with the ZIP entry and input stream for
     * the note content.
     */
    private static Map.Entry<ZipEntry,InputStream> makeNoteFile(
            String directory, String note) {
        StringBuilder fileName = new StringBuilder();
        if (directory != null)
            fileName.append(directory);
        fileName.append(SRAND.nextAlphabetic(5, 30)).append(".txt");
        InputStream fileStream = new ByteArrayInputStream(
                note.getBytes(StandardCharsets.UTF_8));
        ZipEntry fileEntry = new ZipEntry(fileName.toString());
        return Map.entry(fileEntry, fileStream);
    }

    /**
     * Test importing notes from a ZIP file not created by our
     * {@link ZIPExporter}.  Regardless of the import type, these should be
     * added to any existing notes.
     */
    @Test
    public void testImportExternalNotes()
            throws IOException, JSONException {

        addRandomNotes();

        String newCategory = SRAND.nextAlphabetic(8);
        String catDirectory = newCategory + File.separator;
        String unfiledNote = randomParagraph();
        String filedNote = randomParagraph();
        Map.Entry<ZipEntry,InputStream> unfiledEntry = makeNoteFile(
                null, unfiledNote);
        Map.Entry<ZipEntry,InputStream> filedEntry = makeNoteFile(
                catDirectory, filedNote);
        List<Map.Entry<ZipEntry,InputStream>> files = new ArrayList<>();
        files.add(unfiledEntry);
        files.add(filedEntry);

        File zipFile = createTestZip("external", false,
                Collections.singletonList(new ZipEntry(catDirectory)), files);

        // Check the initial data set
        List<NoteCategory> initialCategories = mockRepo.getCategories();
        List<NoteItem> initialNotes = readNotes();

        runImporter(zipFile, ImportType.CLEAN, false, null);

        // Check the new data set; we expect one new category and two new notes.
        List<NoteCategory> actualCategories = mockRepo.getCategories();
        List<NoteItem> actualNotes = readNotes();
        actualCategories.removeAll(initialCategories);
        actualNotes.removeAll(initialNotes);
        assertEquals("Number of imported notes",
                2, actualNotes.size());
        assertEquals("Number of imported categories",
                1, actualCategories.size());

        // We won't know which note is which, so first
        // check which category each note is in.
        NoteItem actualUnfiledNote = null;
        NoteItem actualFiledNote = null;
        for (NoteItem note : actualNotes) {
            if (note.getCategoryId() == NoteCategory.UNFILED) {
                assertNull("Both imported notes are Unfiled",
                        actualUnfiledNote);
                actualUnfiledNote = note;
            } else {
                assertNull("Both imported notes are filed",
                        actualFiledNote);
                actualFiledNote = note;
            }
        }
        assertNotNull("No unfiled note was imported", actualUnfiledNote);
        assertNotNull("No filed note was imported", actualFiledNote);
        assertEquals("Content of imported unfiled note",
                unfiledNote, actualUnfiledNote.getNote());
        assertEquals("Newly imported category",
                newCategory, actualCategories.get(0).getName());
        assertEquals(String.format(Locale.US,
                "Content of imported %s note", newCategory),
                filedNote, actualFiledNote.getNote());
        assertFalse("Imported unfiled note is marked private",
                actualUnfiledNote.isPrivate());
        assertFalse(String.format(Locale.US,
                "Imported %s note is marked private", newCategory),
                actualFiledNote.isPrivate());
    }

    /**
     * Test importing notes encrypted with ZIP AES
     *
     * @param method the ZIP encryption method to test
     * @param strength the strength of the AES key to use,
     * if {@code method} is {@link EncryptionMethod#AES};
     * ignored otherwise.
     * @param encryptLocal whether the notes stored in our repository
     * should be encrypted
     *
     * @throws IOException if there was an error creating or
     * reading back the import file.
     */
    private void runImportZIPEncryptedNoteTest(
            EncryptionMethod method, AesKeyStrength strength,
            boolean encryptLocal)
            throws IOException {
        final String plainNoteText = randomParagraph();
        File testFile = File.createTempFile(
                "notes-encrypted-" + method.name(), ".zip");
        testFile.deleteOnExit();
        String entryName = SRAND.nextAlphabetic(10) + ".txt";
        char[] zipPassword = SRAND.nextAlphanumeric(12).toCharArray();
        char[] localPassword = encryptLocal
                ? SRAND.nextAlphanumeric(15).toCharArray() : null;
        if (encryptLocal) {
            globalEncryption.setPassword(localPassword);
            globalEncryption.addSalt();
            globalEncryption.storePassword(mockRepo);
        }

        try (ZipFile zipOut = new ZipFile(testFile)) {
            zipOut.setPassword(zipPassword);
            ZipParameters params = new ZipParameters();
            params.setEncryptFiles(true);
            params.setEncryptionMethod(method);
            if (method == EncryptionMethod.AES)
                params.setAesKeyStrength(strength);
            params.setFileNameInZip(entryName);
            zipOut.addStream(new ByteArrayInputStream(
                            plainNoteText.getBytes(StandardCharsets.UTF_8)),
                    params);
        }

        runImporter(testFile, ImportType.CLEAN, true, zipPassword);
    }

    @Test
    public void testImportZIPAES128EncryptedNoteToPlain() throws IOException {
        runImportZIPEncryptedNoteTest(EncryptionMethod
                        .AES, AesKeyStrength.KEY_STRENGTH_128, false);
    }

    @Test
    public void testImportZIPAES128EncryptedNoteToReencrypt() throws IOException {
        runImportZIPEncryptedNoteTest(EncryptionMethod
                        .AES, AesKeyStrength.KEY_STRENGTH_128, true);
    }

    @Test
    public void testImportZIPAES256EncryptedNoteToPlain() throws IOException {
        runImportZIPEncryptedNoteTest(EncryptionMethod
                        .AES, AesKeyStrength.KEY_STRENGTH_256, false);
    }

    @Test
    public void testImportZIPAES256EncryptedNoteToReencrypt() throws IOException {
        runImportZIPEncryptedNoteTest(EncryptionMethod
                        .AES, AesKeyStrength.KEY_STRENGTH_256, true);
    }

    // FIXME: Zip4j does not support "standard strong" ZIP encryption
    public void testImportZIPStrongEncryptedNoteToPlain() throws IOException {
        runImportZIPEncryptedNoteTest(EncryptionMethod
                .ZIP_STANDARD_VARIANT_STRONG, null, false);
    }

    // FIXME: Zip4j does not support "standard strong" ZIP encryption
    public void testImportZIPStrongEncryptedNoteToReencrypt() throws IOException {
        runImportZIPEncryptedNoteTest(EncryptionMethod
                .ZIP_STANDARD_VARIANT_STRONG, null, true);
    }

    @Test
    public void testImportZIPWeakEncryptedNoteToPlain() throws IOException {
        runImportZIPEncryptedNoteTest(EncryptionMethod
                .ZIP_STANDARD, null, false);
    }

    @Test
    public void testImportZIPWeakEncryptedNoteToReencrypt() throws IOException {
        runImportZIPEncryptedNoteTest(EncryptionMethod
                .ZIP_STANDARD, null, true);
    }

}
